import type { EmailListItem } from "./types";

// Fixed reference timestamp so the same ISO string is rendered on the server
// and on the client. Prevents hydration mismatches that any `Date.now()` call
// at module load would introduce.
const REFERENCE_NOW = Date.parse("2026-05-10T00:00:00.000Z");
const minutesAgo = (n: number) => new Date(REFERENCE_NOW - n * 60_000).toISOString();

const PROVIDER = "ollama:llama3.1:8b";

export const MOCK_EMAILS: EmailListItem[] = [
  {
    id: 1,
    account_id: 1,
    thread_id: 1,
    from_name: "Anna Mortensen",
    from_email: "anna.mortensen@nordpay.dk",
    subject: "Final review of the integration spec, needed by Tuesday",
    snippet:
      "Hi Dmytro, the security team flagged two open questions on the webhook signing flow we discussed last Thursday...",
    received_at: minutesAgo(22),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "en",
      classification: "urgent",
      confidence: 0.94,
      summary:
        "NordPay's security team wants a one-pager on the two open webhook signing questions, signed off before Wednesday's board review.",
      summary_locale: "en",
      suggested_action: "Send a draft of the one-pager by Tuesday EOD.",
      provider: PROVIDER,
    },
  },
  {
    id: 2,
    account_id: 1,
    thread_id: 2,
    from_name: "GitHub",
    from_email: "noreply@github.com",
    subject: "[anthropics/claude-code] PR #1842: Add retry logic to token refresh",
    snippet:
      "@sven-rasmussen requested your review on PR #1842. 14 files changed, +312 -47.",
    received_at: minutesAgo(95),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "en",
      classification: "important",
      confidence: 0.88,
      summary:
        "Sven requested your review on PR #1842 (retry logic for token refresh, 14 files).",
      summary_locale: "en",
      suggested_action: "Open the PR and leave a review within 48 hours.",
      provider: PROVIDER,
    },
  },
  {
    id: 3,
    account_id: 1,
    thread_id: 3,
    from_name: "Олександр Шевченко",
    from_email: "alex.shevchenko@kyivlabs.ua",
    subject: "Можемо обговорити твій MCP сервер?",
    snippet: "Привіт! Бачив твій PolyPalace на GitHub. У нас в команді є кілька питань...",
    received_at: minutesAgo(240),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "uk",
      classification: "important",
      confidence: 0.81,
      summary:
        "Oleksandr from KyivLabs wants a 20-minute call on Friday about your PolyPalace MCP server.",
      summary_locale: "en",
      suggested_action: "Propose three time slots on Friday.",
      provider: PROVIDER,
    },
  },
  {
    id: 4,
    account_id: 1,
    thread_id: 4,
    from_name: "Stripe",
    from_email: "receipts@stripe.com",
    subject: "Your invoice from Anthropic, $24.18 USD",
    snippet: "Anthropic has sent you a receipt. Total: $24.18 USD on May 9, 2026.",
    received_at: minutesAgo(380),
    is_unread: false,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "en",
      classification: "transactional",
      confidence: 0.97,
      summary: "Anthropic Claude API receipt for April: $24.18 charged to Visa ending 4218.",
      summary_locale: "en",
      suggested_action: "No action needed. Archive.",
      provider: PROVIDER,
    },
  },
  {
    id: 5,
    account_id: 1,
    thread_id: 5,
    from_name: "Вечерний разработчик",
    from_email: "newsletter@dev-vechera.ru",
    subject: "Дайджест 9 мая: что обсуждают в мире AI инфраструктуры",
    snippet: "Подборка статей за неделю: Anthropic запускает MCP 2.0, OpenRouter поднимает...",
    received_at: minutesAgo(540),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "ru",
      classification: "newsletter",
      confidence: 0.99,
      summary:
        "Russian AI-infra digest. Anthropic MCP 2.0 streaming is the headline; worth a look if PolyPalace gets expanded.",
      summary_locale: "en",
      suggested_action: "Save the MCP 2.0 link. Archive the rest.",
      provider: PROVIDER,
    },
  },
  {
    id: 6,
    account_id: 1,
    thread_id: 6,
    from_name: "Hacker News Daily",
    from_email: "digest@hnrss.org",
    subject: "Top 10 stories: Show HN: I built an email AI agent in a weekend",
    snippet: "Show HN: I built an email AI agent in a weekend (847 points, 234 comments)...",
    received_at: minutesAgo(720),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "en",
      classification: "newsletter",
      confidence: 0.99,
      summary:
        "HN digest. Top story is someone shipping a weekend email AI agent (847 points). Possible competitor.",
      summary_locale: "en",
      suggested_action: "Read the top HN story; it is directly adjacent to MailPalace.",
      provider: PROVIDER,
    },
  },
  {
    id: 7,
    account_id: 1,
    thread_id: 7,
    from_name: "Skat.dk",
    from_email: "noreply@skat.dk",
    subject: "Din årsopgørelse for 2025 er klar",
    snippet: "Hej Dmytro, din årsopgørelse for indkomståret 2025 er nu tilgængelig...",
    received_at: minutesAgo(900),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "da",
      classification: "important",
      confidence: 0.92,
      summary:
        "Skat.dk: your 2025 årsopgørelse is ready in TastSelv. Worth a quick check for adjustments.",
      summary_locale: "en",
      suggested_action: "Log into skat.dk next week and review.",
      provider: PROVIDER,
    },
  },
  {
    id: 8,
    account_id: 1,
    thread_id: 8,
    from_name: "Notion",
    from_email: "team@notion.so",
    subject: "Your weekly digest: 14 pages updated",
    snippet: "Here is what changed in your workspace this week. 14 pages were updated...",
    received_at: minutesAgo(1100),
    is_unread: false,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "en",
      classification: "newsletter",
      confidence: 0.98,
      summary: "Notion weekly digest: 14 pages updated, 3 new comments on Q2 product roadmap.",
      summary_locale: "en",
      suggested_action: "Archive. Open the Q2 roadmap comments directly in Notion.",
      provider: PROVIDER,
    },
  },
  {
    id: 9,
    account_id: 1,
    thread_id: 9,
    from_name: "Linear",
    from_email: "no-reply@linear.app",
    subject: "MAIL-12: New issue assigned to you",
    snippet: 'MAIL-12: "Add Russian draft generation" assigned to dmytro by sven-rasmussen.',
    received_at: minutesAgo(1500),
    is_unread: false,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "en",
      classification: "important",
      confidence: 0.86,
      summary:
        "Linear MAIL-12 assigned to you: draft generator should match the source language for Russian emails.",
      summary_locale: "en",
      suggested_action: "Accept the issue or ask Sven for clarification.",
      provider: PROVIDER,
    },
  },
  {
    id: 10,
    account_id: 1,
    thread_id: 10,
    from_name: "Klarna",
    from_email: "info@klarna.dk",
    subject: "Spar 30% hos H&M denne uge",
    snippet: "Du har en eksklusiv rabat hos H&M frem til søndag. Brug koden KLARNA30...",
    received_at: minutesAgo(1800),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "da",
      classification: "promotion",
      confidence: 0.99,
      summary: "Klarna H&M promotion. Safe to archive.",
      summary_locale: "en",
      suggested_action: "Archive.",
      provider: PROVIDER,
    },
  },
];
