import type { EmailListItem } from "./types";

const minutesAgo = (n: number) => new Date(Date.now() - n * 60_000).toISOString();

export const MOCK_EMAILS: EmailListItem[] = [
  {
    id: 1,
    account_id: 1,
    thread_id: 1,
    from_name: "Anna Mortensen",
    from_email: "anna.mortensen@nordpay.dk",
    subject: "Final review of the integration spec — needed by Tuesday",
    snippet:
      "Hi Dmytro, the security team flagged two open questions on the webhook signing flow we discussed last Thursday...",
    received_at: minutesAgo(22),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "en",
      classification: "urgent",
      confidence: 0.94,
      summary_ru:
        "Анна из NordPay просит однопэйджер по двум вопросам безопасности вебхуков до вторника. Совет директоров в среду.",
      suggested_action: "Ответить с черновиком документа до вторника, 18:00.",
      provider: "ollama:llama3.1:8b",
    },
  },
  {
    id: 2,
    account_id: 1,
    thread_id: 2,
    from_name: "GitHub",
    from_email: "noreply@github.com",
    subject: "[anthropics/claude-code] PR #1842: Add retry logic to token refresh",
    snippet:
      "@sven-rasmussen requested your review on PR #1842. 14 files changed, +312 -47.",
    received_at: minutesAgo(95),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "en",
      classification: "important",
      confidence: 0.88,
      summary_ru: "Свен попросил тебя ревью на PR #1842. Логика ретраев для refresh токена. 14 файлов.",
      suggested_action: "Открыть PR и оставить ревью в течение 48 часов.",
      provider: "ollama:llama3.1:8b",
    },
  },
  {
    id: 3,
    account_id: 1,
    thread_id: 3,
    from_name: "Олександр Шевченко",
    from_email: "alex.shevchenko@kyivlabs.ua",
    subject: "Можемо обговорити твій MCP сервер?",
    snippet:
      "Привіт! Бачив твій PolyPalace на GitHub. У нас в команді є кілька питань...",
    received_at: minutesAgo(240),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "uk",
      classification: "important",
      confidence: 0.81,
      summary_ru: "Олександр з KyivLabs хочет 20-минутный созвон в пятницу про твой PolyPalace MCP.",
      suggested_action: "Предложить три временных слота на пятницу.",
      provider: "ollama:llama3.1:8b",
    },
  },
  {
    id: 4,
    account_id: 1,
    thread_id: 4,
    from_name: "Stripe",
    from_email: "receipts@stripe.com",
    subject: "Your invoice from Anthropic — $24.18 USD",
    snippet: "Anthropic has sent you a receipt. Total: $24.18 USD on May 9, 2026.",
    received_at: minutesAgo(380),
    is_unread: false,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "en",
      classification: "transactional",
      confidence: 0.97,
      summary_ru: "Чек от Anthropic на $24.18 за апрельский Claude API. Карта 4218.",
      suggested_action: "Ничего не требуется. Архивировать.",
      provider: "ollama:llama3.1:8b",
    },
  },
  {
    id: 5,
    account_id: 1,
    thread_id: 5,
    from_name: "Вечерний разработчик",
    from_email: "newsletter@dev-vechera.ru",
    subject: "Дайджест 9 мая: что обсуждают в мире AI инфраструктуры",
    snippet:
      "Подборка статей за неделю: Anthropic запускает MCP 2.0, OpenRouter поднимает...",
    received_at: minutesAgo(540),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "ru",
      classification: "newsletter",
      confidence: 0.99,
      summary_ru: "Дайджест AI инфры. MCP 2.0 от Anthropic — стоит проверить если расширяешь PolyPalace.",
      suggested_action: "Сохранить ссылку на MCP 2.0 анонс. Остальное архивировать.",
      provider: "ollama:llama3.1:8b",
    },
  },
  {
    id: 6,
    account_id: 1,
    thread_id: 6,
    from_name: "Hacker News Daily",
    from_email: "digest@hnrss.org",
    subject: "Top 10 stories — Show HN: I built an email AI agent in a weekend",
    snippet:
      "Show HN: I built an email AI agent in a weekend (847 points, 234 comments)...",
    received_at: minutesAgo(720),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "en",
      classification: "newsletter",
      confidence: 0.99,
      summary_ru:
        "HN дайджест. Топ — кто-то зашипил email AI агента за выходные. 847 points. Конкурент?",
      suggested_action: "Прочитать первый стори на HN — релевантно нашему проекту.",
      provider: "ollama:llama3.1:8b",
    },
  },
  {
    id: 7,
    account_id: 1,
    thread_id: 7,
    from_name: "Skat.dk",
    from_email: "noreply@skat.dk",
    subject: "Din årsopgørelse for 2025 er klar",
    snippet:
      "Hej Dmytro, din årsopgørelse for indkomståret 2025 er nu tilgængelig...",
    received_at: minutesAgo(900),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "da",
      classification: "important",
      confidence: 0.92,
      summary_ru: "Скат.дк: твоя налоговая декларация за 2025 готова. Зайти в TastSelv проверить.",
      suggested_action: "Открыть skat.dk на следующей неделе и проверить.",
      provider: "ollama:llama3.1:8b",
    },
  },
  {
    id: 8,
    account_id: 1,
    thread_id: 8,
    from_name: "Notion",
    from_email: "team@notion.so",
    subject: "Your weekly digest: 14 pages updated",
    snippet:
      "Here is what changed in your workspace this week. 14 pages were updated...",
    received_at: minutesAgo(1100),
    is_unread: false,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "en",
      classification: "newsletter",
      confidence: 0.98,
      summary_ru: "Notion недельный дайджест. 14 страниц, 3 комментария на Q2 роадмап.",
      suggested_action: "Архивировать. Проверить комментарии в Notion напрямую.",
      provider: "ollama:llama3.1:8b",
    },
  },
  {
    id: 9,
    account_id: 1,
    thread_id: 9,
    from_name: "Linear",
    from_email: "no-reply@linear.app",
    subject: "MAIL-12: New issue assigned to you",
    snippet:
      'MAIL-12: "Add Russian draft generation" assigned to dmytro by sven-rasmussen.',
    received_at: minutesAgo(1500),
    is_unread: false,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "en",
      classification: "important",
      confidence: 0.86,
      summary_ru: "Linear: новая задача MAIL-12 на тебя. Драфты на русском когда исходник на русском.",
      suggested_action: "Принять задачу или попросить уточнения у Свена.",
      provider: "ollama:llama3.1:8b",
    },
  },
  {
    id: 10,
    account_id: 1,
    thread_id: 10,
    from_name: "Klarna",
    from_email: "info@klarna.dk",
    subject: "Spar 30% hos H&M denne uge",
    snippet:
      "Du har en eksklusiv rabat hos H&M frem til søndag. Brug koden KLARNA30...",
    received_at: minutesAgo(1800),
    is_unread: true,
    is_starred: false,
    has_attachments: false,
    ai: {
      language: "da",
      classification: "promotion",
      confidence: 0.99,
      summary_ru: "Кларна реклама H&M. Можно архивировать.",
      suggested_action: "Архивировать.",
      provider: "ollama:llama3.1:8b",
    },
  },
];
